import { createStore } from "vuex";
import Game from "./modules/Game";
import Debug from "./modules/Debug";
import Board from "./modules/Board";
import Tiles from "./modules/Tiles";
import Players from "./modules/Players";
import Logs from "./modules/Logs";
import Meeple from "./modules/Meeple";
import CPU from "./modules/CPU";
import Graphics from "./modules/Graphics";
export default createStore({ modules: { Game, Board, Tiles, Debug, Players, Logs, CPU, Meeple, Graphics } });
